export const FETCH_ALARM_LIST = 'FETCH_ALARM_LIST' as const
export const FETCH_ALARM_LIST_SAGA_FAILURE = 'FETCH_ALARM_LIST_SAGA_FAILURE' as const
export const FETCH_ALARM_LIST_SAGA_SUCCESS = 'FETCH_ALARM_LIST_SAGA_SUCCESS' as const
export const RELEASE_ALARM_ITEM = 'RELEASE_ALARM_ITEM' as const

export const FETCH_ALARM_ITEM = 'FETCH_ALARM_ITEM' as const
export const FETCH_ALARM_ITEM_SAGA_FAILURE = 'FETCH_ALARM_ITEM_SAGA_FAILURE' as const
export const FETCH_ALARM_ITEM_SAGA_SUCCESS = 'FETCH_ALARM_ITEM_SAGA_SUCCESS' as const
